# Generated by Django 2.2.24 on 2021-07-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oinkerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oinkerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
